name: Deploy Vite Project

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Viktigt för att kunna deploya till gh-pages
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd ecom1
          npm ci  # Använder ci istället för install för mer pålitliga builds

      - name: Build project
        run: |
          cd ecom1
          npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ecom1/dist
          branch: gh-pages
          clean: true  # Rensar gamla filer
          token: ${{ secrets.GITHUB_TOKEN }}  # Explicit token definition
 